#!/bin/bash
#Purpose: Real Time CPU utilization Monitoring
#Version:1.0
#Created Date: Tue March 24 2:16 EST 2020
#Modified Date: 
#Author: Eugne Loh
# START #

PATHS="/"
HOSTNAME=$(hostname)
CRITICAL=98
WARNING=90
CRITICALMail="0125919@kdu-online.com"
MAILWAR="0125919@kdu-online.com"
mkdir -p /var/log/cputilhist
LOGFILE=/var/log/cputilhist/cpusage- `date +%h%d%y`.log

touch $LOGFILE

for path in $PATHS
do
	CPULOAD=`top -b -n 2 -d1 | grep "Cpu(s)" | tail -n1 | awk '{print $2}' |awk -F. '{print $1}' `
if [ -n $WARNING -a -n $CRITICAL ]; then
if [ "$CPULOAD" -ge "$WARNING" -a "$CPULOAD" -1t "$CRITICAL" ]; then
	echo "`date "+%F %H:%M:%S"` WARNING - $CPULOAD on Host $HOSTNAME" >> $LOGFILE
	echo "Warning Cpuload $CPULOAD Host is $HOSTNAME" | mail -s "CPULOAD is Warning" $MAILWAR
	exit 1
elif [ "$CPULOAD" -ge "$CRITICAL" ]; then
	echo "`date "+%F %H:%M:%S"` CRITICAL - $CPULOAD on Host $HOSTNAME" >> $LOGFILE
	echo "Warning Cpuload $CPULOAD Host is $HOSTNAME" | mail -s "CPULOAD is Warning" $CRITICALMail
	exit 2
else 
	echo "`date "+%F %H:%M:%S"` OK -$CPULOAD on $HOSTNAME" >> $LOGFILE
	exit 0
fi
fi
done

#END#
